from enum import Enum

class TaskType(str, Enum):
    VQA = "VQA"
    GROUNDING = "GROUNDING"
    CHANGE = "CHANGE"
    OPTICAL_SAR = "OPTICAL_SAR"
    UNKNOWN = "UNKNOWN"

class RunStatus(str, Enum):
    QUEUED = "QUEUED"
    VALIDATING_INPUT = "VALIDATING_INPUT"
    INTERPRETING_QUERY = "INTERPRETING_QUERY"
    PLANNING = "PLANNING"
    RUNNING_SPECIALIST = "RUNNING_SPECIALIST"
    GENERATING_EVIDENCE = "GENERATING_EVIDENCE"
    COMPLETED = "COMPLETED"

class FailureStatus(str, Enum):
    VALIDATION_FAILED = "VALIDATION_FAILED"
    UNSUPPORTED_TASK = "UNSUPPORTED_TASK"
    SPECIALIST_UNAVAILABLE = "SPECIALIST_UNAVAILABLE"
    SPECIALIST_FAILED = "SPECIALIST_FAILED"
    EVIDENCE_FAILED = "EVIDENCE_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"

class InputConfigType(str, Enum):
    SINGLE_IMAGE = "SINGLE_IMAGE"
    BI_TEMPORAL = "BI_TEMPORAL"
    OPTICAL_SAR = "OPTICAL_SAR"
