from enum import Enum

class TaskType(str, Enum):
    VQA = "VQA"
    GROUNDING = "GROUNDING"
    CHANGE = "CHANGE"
    OPTICAL_SAR = "OPTICAL_SAR"
    UNKNOWN = "UNKNOWN"

class RunStatus(str, Enum):
    QUEUED = "QUEUED"
    VALIDATING_INPUT = "VALIDATING_INPUT"
    INTERPRETING_QUERY = "INTERPRETING_QUERY"
    PLANNING = "PLANNING"
    RUNNING_SPECIALIST = "RUNNING_SPECIALIST"
    GENERATING_EVIDENCE = "GENERATING_EVIDENCE"
    COMPLETED = "COMPLETED"

class FailureStatus(str, Enum):
    VALIDATION_FAILED = "VALIDATION_FAILED"
    UNSUPPORTED_TASK = "UNSUPPORTED_TASK"
    SPECIALIST_UNAVAILABLE = "SPECIALIST_UNAVAILABLE"
    SPECIALIST_FAILED = "SPECIALIST_FAILED"
    EVIDENCE_FAILED = "EVIDENCE_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    EMPTY_QUERY = "EMPTY_QUERY"
    NO_INPUT = "NO_INPUT"
    INVALID_INPUT_COUNT = "INVALID_INPUT_COUNT"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    INVALID_CONFIGURATION = "INVALID_CONFIGURATION"
    MISSING_MODALITY = "MISSING_MODALITY"
    TEMPORAL_PAIR_REQUIRED = "TEMPORAL_PAIR_REQUIRED"
    OPTICAL_SAR_PAIR_REQUIRED = "OPTICAL_SAR_PAIR_REQUIRED"
    UNSUPPORTED_TASK_CONFIGURATION = "UNSUPPORTED_TASK_CONFIGURATION"

class InputConfigType(str, Enum):
    SINGLE_IMAGE = "SINGLE_IMAGE"
    BI_TEMPORAL = "BI_TEMPORAL"
    OPTICAL_SAR = "OPTICAL_SAR"
